# -*- mode: ruby -*-
# vi: set ft=ruby :

local_interface = ENV["DEFAULT_INTERFACE"] || ""

Vagrant.configure("2") do |config|
  config.vm.box = "getupcloud/desafio-linux"
  config.vm.box_version = "1.0.0"
  config.vm.network "public_network", bridge: local_interface
  config.vm.provider "virtualbox"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
end
